---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    branches:
      - dependabot/bundler/ruby/business-2.3.0/.github/dependabot.yml
  - package-ecosystem: npm
    directory: "/javascript"
    schedule:
      interval: "daily"
    branches:
      - dependabot/bundler/ruby/business-2.3.0/.github/dependabot.yml
  - package-ecosystem: bundler
    directory: "/ruby"
    schedule:
      interval: "daily"
    branches:
      - dependabot/bundler/ruby/business-2.3.0/.github/dependabot.yml
