#add verion updates
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    branches:
      - dev
      - dependabot/bundler/ruby/business-2.3.0/.github/dependabot.yml
      - dependabot/bundler/ruby/uk_phone_numbers-0.1.1/.github/dependabot.yml
  - package-ecosystem: npm
    directory: "/javascript"
    schedule:
      interval: "daily"
    branches:
      - dev
      - dependabot/bundler/ruby/business-2.3.0/.github/dependabot.yml
      - dependabot/bundler/ruby/uk_phone_numbers-0.1.1/.github/dependabot.yml
  - package-ecosystem: bundler
    directory: "/ruby"
    schedule:
      interval: "daily"
    branches:
      - dev
      - dependabot/bundler/ruby/business-2.3.0/.github/dependabot.yml
      - dependabot/bundler/ruby/uk_phone_numbers-0.1.1/.github/dependabot.yml
  - package-ecosystem: pip
    directory: "/.py"
    schedule:
      interval: "daily"
    branches:
      - dev
      - dependabot/bundler/ruby/business-2.3.0/.github/dependabot.yml
      - dependabot/bundler/ruby/uk_phone_numbers-0.1.1/.github/dependabot.yml
