#add verion updates
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    branches:
      - dev
  - package-ecosystem: npm
    directory: "/javascript"
    schedule:
      interval: "weekly"
    branches:
      - dev
  - package-ecosystem: bundler
    directory: "/ruby"
    schedule:
      interval: "weekly"
    branches:
      - dev
